### ISSUE TITLE
SDPT3-4 fails  in MATLAB 2016b on ubuntu

### ISSUE THREAD

**Issue by nothing2wang** [sqlp/sdpt3#3]
>>>startup
>> [blk,At,C,b]=read_sdpa('./sdplib/mcp250-1.dat-s');
>> [obj,X,y,Z,info]=sqlp(blk,At,C,b);
It runs on windows fine! but it runs on ubuntu fails. I use matlab2016b on both OS.
 
num. of constraints = 250
 dim. of sdp    var  = 250,   num. of sdp  blk  =  1Error using mexschurfun
mexschurfun: requires no output argument.

Error in checkdepconstr (line 110)
   AAt = mexschurfun(AAt,rho*max(diagAAt,1));

Error in sqlpmain (line 85)
   [At,b,y,indeprows,par.depconstr,feasible,par.AAt] = ...

Error in sqlp (line 243)
        sqlpmain(blk3,At3,C3,b,par,parbarrier3,X03,y0,Z03);

So I want to know this codes only on windows? but I don't see the that in paper or code.

**Comment by johanlofberg** [comment]
sdpt3 does not work on matlab2016b, it's just a lucky case on windows in your case. See #2

**Comment by nothing2wang** [comment]
thanks a lot !

**Comment by marcelofmmartines** [comment]
I received the same message while running "sqlpdemo" during instalation process:
num. of constraints = 10
 dim. of sdp    var  = 10,   num. of sdp  blk  =  1??? Error using ==> mexschurfun
mexschurfun: requires no output argument.

Error in ==> checkdepconstr at 110
   AAt = mexschurfun(AAt,rho*max(diagAAt,1));

Error in ==> sqlpmain at 85
   [At,b,y,indeprows,par.depconstr,feasible,par.AAt] = ...

Error in ==> sqlp at 242
   [obj,X3,y,Z3,info,runhist] = ...

Error in ==> sqlpdemo at 80
           [obj,X,y,Z,infoall,runhist] = ...
 and I'm using Matlab R2011a on windows 7-32 bits, someone knows why?

**Comment by siko1056** [comment]
Answered in issue #7 .
