### ISSUE TITLE
MEX files need to be recompiled for R2017a

### ISSUE THREAD

**Issue by mcg1969** [sqlp/sdpt3#4]
I'm finding that CVX's mex files, which include SeDuMI and SDPT3, are incompatible with MATLAB R2017a. This is quite unfortunate ;-( it is not clear to me if we can recompile them in a manner which is compatible with pre-R2017a versions as well, and if not, we'd have to make sure we can host both binaries somehow.

**Comment by siko1056** [comment]
A possible solution would be to deploy the binaries for the specific MATLAB releases in separate folders, for example

    Solver/Mexfun/R2017a/...
    Solver/Mexfun/R2016b/...

like it partially happened for the Windows version of Octave 4.0 and older versions using the `o_win` directory. Those directories can be included in the `install_sdpt3.m` script by switching the output of the [ver](https://www.mathworks.com/help/matlab/ref/ver.html) command for example.

A drawback would be more binaries in the repository. To overcome this issue it would be nice to make use of the [release feature](https://help.github.com/articles/distributing-large-binaries/) of Github, that allows you to deploy an arbitrary amount of binaries alongside each release and leave the repository for pure source code.

The same could be done for [SeDuMi](https://github.com/sqlp/sedumi/issues/25) as well.

**Comment by mcg1969** [comment]
That certainly seems like a reasonable approach.

**Comment by mcg1969** [comment]
I'm closing this because we're now compiling the MEX files in CI using the oldest functioning MATLAB versions available in GitHub actions.
