### ISSUE TITLE
Problem installation SDPT3-4.0 and matlab 2011a-32bits

### ISSUE THREAD

**Issue by marcelofmmartines** [sqlp/sdpt3#7]
Hi.
I received the message while running "sqlpdemo" during instalation process of SDPT3-4.0:
num. of constraints = 10
dim. of sdp var = 10, num. of sdp blk = 1??? Error using ==> mexschurfun
mexschurfun: requires no output argument.

Error in ==> checkdepconstr at 110
AAt = mexschurfun(AAt,rho*max(diagAAt,1));

Error in ==> sqlpmain at 85
[At,b,y,indeprows,par.depconstr,feasible,par.AAt] = ...

Error in ==> sqlp at 242
[obj,X3,y,Z3,info,runhist] = ...

Error in ==> sqlpdemo at 80
[obj,X,y,Z,infoall,runhist] = ...

and I'm using Matlab R2011a on windows 7-32 bits, someone knows why?
Thanks in advance

**Comment by johanlofberg** [comment]
Sounds like you re mixing versions, i.e., old binaries and new MATLAB code. You probably have to recompile the 32-bit binaries

**Comment by marcelofmmartines** [comment]
Sorry for my ignorance, but what do you mean with " recompile the 32-bit binaries"?

**Comment by johanlofberg** [comment]
Run install_sdpt3 to generate new binaries. They appear to be compiled for the previous version of sdpt3 where some functions did manipulations on indata and not returning any output (that's what the error message appears to say. The binary assumes no output, but the MATLAB file uses an output argument

**Comment by marcelofmmartines** [comment]
I ran "install_sdpt3" and after I ran "install_sdpt3 -rebuild" and I got this message:
SDPT3 installation script
   Directory: C:\SDPT3-4.0
   Matlab 7.12.0.635 (R2011a) on PCWIN
---------------------------------------------------------------------------
Looking for existing binaries...found!
   If for some reason you need to rebuild the binaries, use this command:
      install_sdpt3 -rebuild
---------------------------------------------------------------------------
Adding SDPT3 to the Matlab path:
   Base...already there.
   Solver...already there.
   HSDSolver...already there.
   Binaries...already there.
   Examples...already there.
---------------------------------------------------------------------------
SDPT3 has been succesfully installed.
For more information, type "help sdpt3" or see the user guide.
---------------------------------------------------------------------------

>>  install_sdpt3 -rebuild

---------------------------------------------------------------------------
SDPT3 installation script
   Directory: C:\SDPT3-4.0
   Matlab 7.12.0.635 (R2011a) on PCWIN
---------------------------------------------------------------------------
Attempting to recompile the SDPT3 binaries:
??? Undefined function or variable 'IS64BIT'.

Error in ==> install_sdpt3 at 112
            if IS64BIT, dirval = 'win64'; else dirval = 'win32'; end

**Comment by johanlofberg** [comment]
looks like a bug since there is no such function nor is it defined. However, since you know you're running 32bit, just edit the file to set dirval directly

**Comment by marcelofmmartines** [comment]
Okay. Thank you for your attention johanlofberg!
 I followed your tip and put "dirval = 'win32';" at 112 line and It worked perfectly now!
Very thanks!
