### ISSUE TITLE
Installation Issue Matlab2017a

### ISSUE THREAD

**Issue by ja00342** [sqlp/sdpt3#9]
I have been having a problem reinstalling SDPT3-4.0 on Matlab2017a. I was previously working but some issue has meant I have had to reinstall. Now, when I follow the installation instructions I receive the following messages and error:

>> Installmex(1)
 current directory is:  Z:\JoeAllen\MatlabFiles\SDPT3-4.0

 Now compiling the mexFunctions in:
 Z:\JoeAllen\MatlabFiles\SDPT3-4.0\Solver\Mexfun
 mex -O -largeArrayDims  -output mexProd2  mexProd2.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexProd2nz  mexProd2nz.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexinprod  mexinprod.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexmat  mexmat.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexsmat  mexsmat.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexsvec  mexsvec.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexschur  mexschur.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
Z:\JoeAllen\MatlabFiles\SDPT3-4.0\Solver\Mexfun\mexschur.c: In function 'mexFunction':
Z:\JoeAllen\MatlabFiles\SDPT3-4.0\Solver\Mexfun\mexschur.c:370:5: warning: incompatible implicit declaration of built-in function 'memcpy'
     memcpy(schur,mxGetPr(prhs[9]),(m*m)*sizeof(double));    
     ^

MEX completed successfully.
 mex -O -largeArrayDims  -output mexqops  mexqops.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexexpand  mexexpand.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexskron  mexskron.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexnnz  mexnnz.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mexschurfun  mexschurfun.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
Z:\JoeAllen\MatlabFiles\SDPT3-4.0\Solver\Mexfun\mexschurfun.c: In function 'mexFunction':
Z:\JoeAllen\MatlabFiles\SDPT3-4.0\Solver\Mexfun\mexschurfun.c:40:6: warning: incompatible implicit declaration of built-in function 'memcpy'
      memcpy(X,mxGetPr(prhs[0]),nzmax*sizeof(double)); 
      ^
Z:\JoeAllen\MatlabFiles\SDPT3-4.0\Solver\Mexfun\mexschurfun.c:46:5: warning: incompatible implicit declaration of built-in function 'memcpy'
     memcpy(X,mxGetPr(prhs[0]),(n*n)*sizeof(double)); 
     ^

MEX completed successfully.
 mex -O -largeArrayDims  -output mexMatvec  mexMatvec.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mextriang  mextriang.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
 mex -O -largeArrayDims  -output mextriangsp  mextriangsp.c  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwlapack.lib'  'C:\Program Files\MATLAB\R2017a\extern\lib\win64\mingw64\libmwblas.lib'  
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
>> startup
>> sqlpdemo
using feasible starting point? [yes = 1, no = 0] 1

  using feasible starting point

******** random sdp **********
Invalid MEX-file 'Z:\JoeAllen\MatlabFiles\SDPT3-4.0\Solver\Mexfun\mexsvec.mexw64': Access is denied.

.

Error in svec (line 47)
                     x{p}(:,k) = mexsvec(pblk,M{p,k},isspx(p));

Error in randsdp (line 134)
   Avec = svec(blk,A,ones(size(blk,1),1));

Error in sqlpdemo (line 37)
          [blk,At,C,b,X0,y0,Z0] = randsdp(n,[],[],m,feas);

Any ideas on how to fix this?

Thanks

**Comment by siko1056** [comment]
Is your drive "Z:" some network storage, you don't have sufficient access permissions (e.g. execution permissions) to?

**Comment by ja00342** [comment]
I believe I should have sufficient access permission to that drive. Previously this has been where the SDPT3 folder has been and it has run from there.

**Comment by siko1056** [comment]
Do the Matlab standard Mex-Examples work for you on your drive Z:? I think this test is performed quickly: https://www.mathworks.com/help/matlab/matlab_external/standalone-example.html#d119e19784

**Comment by ja00342** [comment]
Hm, no it does not. I am getting the same error message:

>> mex arrayProduct.c
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
>> s=5;
>> A=[1.5, 2.9];
>> B=arrayProduct(s,A)
Invalid MEX-file 'Z:\JoeAllen\MatlabFiles\arrayProduct.mexw64': Access is denied.

**Comment by siko1056** [comment]
And from another local location (for example your users Documents directory)?

**Comment by ja00342** [comment]
Yes, this works on my C: drive. I guess this suggests an access issue with the Z: drive?

**Comment by siko1056** [comment]
Okay, then I guess the issue seems isolated and is totally unrelated to SDPT3. It would be nice if you close this issue, we can keep discussing here.

Maybe you check your drive's preferences (right click on it) especially the access control settings and ask Google how to enforce those permissions for your drive (external [usb?] drive, network drive, ...).
